# Generated by Django 5.2.7 on 2025-10-16 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('EN_EJECUCION', 'EN_EJECUCION'), ('EN_QA', 'EN_QA'), ('CERRADA', 'CERRADA'), ('ANULADA', 'ANULADA')], default='ABIERTA', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('apertura', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_responsable', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='vehicles.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('REPUESTO', 'REPUESTO'), ('SERVICIO', 'SERVICIO')], max_length=20)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorders.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('tipo', models.CharField(choices=[('FOTO', 'FOTO'), ('PDF', 'PDF'), ('OTRO', 'OTRO')], default='FOTO', max_length=10)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='workorders.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultado', models.CharField(choices=[('OK', 'OK'), ('NO_OK', 'NO_OK')], max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('verificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_realizados', to=settings.AUTH_USER_MODEL)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='workorders.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Pausa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='workorders.ordentrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pausas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('umbral', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='workorders.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='workorders.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones', to=settings.AUTH_USER_MODEL)),
                ('presupuesto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aprobacion', to='workorders.presupuesto')),
            ],
        ),
    ]
