# Generated by Django 5.2.7 on 2025-10-16 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itemot',
            index=models.Index(fields=['ot'], name='workorders__ot_id_46eb80_idx'),
        ),
        migrations.AddIndex(
            model_name='itemot',
            index=models.Index(fields=['tipo'], name='workorders__tipo_f2668c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado'], name='workorders__estado_359d13_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['apertura'], name='workorders__apertur_5d43a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemot',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='itemot_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='itemot',
            constraint=models.CheckConstraint(condition=models.Q(('costo_unitario__gte', 0)), name='itemot_costo_gte_0'),
        ),
    ]
