# Generated by Django 5.2.7 on 2025-10-16 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_itemot_workorders__ot_id_46eb80_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=64)),
                ('objeto_tipo', models.CharField(max_length=64)),
                ('objeto_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['objeto_tipo', 'objeto_id'], name='workorders__objeto__e313dc_idx'), models.Index(fields=['accion'], name='workorders__accion_63404e_idx'), models.Index(fields=['ts'], name='workorders__ts_d3fa4e_idx')],
            },
        ),
    ]
