# Generated by Django 5.2.7 on 2025-10-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
