# Generated by Django 5.2.7 on 2025-11-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_evidencia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('EN_EJECUCION', 'EN_EJECUCION'), ('EN_PAUSA', 'EN_PAUSA'), ('EN_QA', 'EN_QA'), ('CERRADA', 'CERRADA'), ('ANULADA', 'ANULADA')], default='ABIERTA', max_length=20),
        ),
    ]
