# Generated by Django 5.2.7 on 2025-11-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(blank=True, default='MEDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo',
            field=models.CharField(blank=True, default='MANTENCION', max_length=50),
        ),
    ]
