# Generated by Django 5.2.7 on 2025-11-17 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_ordentrabajo_prioridad_ordentrabajo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pausa',
            options={'ordering': ['-inicio']},
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Diagnóstico realizado por Jefe de Taller'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_aprobacion_supervisor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_asignacion_mecanico',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_diagnostico',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_inicio_ejecucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='jefe_taller',
            field=models.ForeignKey(blank=True, help_text='Jefe de Taller que valida', limit_choices_to={'rol': 'JEFE_TALLER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_jefe_taller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='mecanico',
            field=models.ForeignKey(blank=True, help_text='Mecánico asignado para ejecución', limit_choices_to={'rol': 'MECANICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor asignado', limit_choices_to={'rol__in': ['SUPERVISOR', 'COORDINADOR_ZONA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='zona',
            field=models.CharField(blank=True, help_text='Zona o sucursal', max_length=100),
        ),
        migrations.AddField(
            model_name='pausa',
            name='es_automatica',
            field=models.BooleanField(default=False, help_text='Indica si es una pausa automática (ej: colación)'),
        ),
        migrations.AddField(
            model_name='pausa',
            name='tipo',
            field=models.CharField(choices=[('ESPERA_REPUESTO', 'Espera de Repuesto'), ('APROBACION_PENDIENTE', 'Aprobación Pendiente'), ('COLACION', 'Colación (12:30-13:15)'), ('OTRO', 'Otro Motivo Operativo'), ('ADMINISTRATIVA', 'Pausa Administrativa')], default='OTRO', help_text='Tipo de pausa', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('EN_DIAGNOSTICO', 'EN_DIAGNOSTICO'), ('EN_EJECUCION', 'EN_EJECUCION'), ('EN_PAUSA', 'EN_PAUSA'), ('EN_QA', 'EN_QA'), ('RETRABAJO', 'RETRABAJO'), ('CERRADA', 'CERRADA'), ('ANULADA', 'ANULADA')], default='ABIERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Responsable general (puede ser supervisor o mecánico)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('MANTENCION', 'Mantención'), ('REPARACION', 'Reparación'), ('EMERGENCIA', 'Emergencia'), ('DIAGNOSTICO', 'Diagnóstico'), ('OTRO', 'Otro')], default='MANTENCION', max_length=50),
        ),
        migrations.AlterField(
            model_name='pausa',
            name='motivo',
            field=models.CharField(help_text='Motivo detallado de la pausa', max_length=255),
        ),
        migrations.AddIndex(
            model_name='pausa',
            index=models.Index(fields=['ot', 'inicio'], name='workorders__ot_id_ca9db8_idx'),
        ),
        migrations.AddIndex(
            model_name='pausa',
            index=models.Index(fields=['tipo', 'inicio'], name='workorders__tipo_dbb9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='pausa',
            index=models.Index(fields=['es_automatica'], name='workorders__es_auto_ce159c_idx'),
        ),
    ]
