# Generated by Django 5.2.7 on 2025-11-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_alter_pausa_options_ordentrabajo_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='tipo',
            field=models.CharField(choices=[('FOTO', 'FOTO'), ('PDF', 'PDF'), ('HOJA_CALCULO', 'HOJA_CALCULO'), ('DOCUMENTO', 'DOCUMENTO'), ('COMPRIMIDO', 'COMPRIMIDO'), ('OTRO', 'OTRO')], default='FOTO', max_length=15),
        ),
    ]
