# Generated by Django 5.2.7 on 2025-11-18 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehiculo_ceco_vehiculo_cumplimiento_and_more'),
        ('workorders', '0008_alter_evidencia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='backup',
            field=models.ForeignKey(blank=True, help_text='Backup asignado durante esta OT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_backup', to='vehicles.backupvehiculo'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='causa_ingreso',
            field=models.TextField(blank=True, help_text='Causa detallada de ingreso al taller'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='causa_salida',
            field=models.TextField(blank=True, help_text='Causa de salida del taller'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado_operativo_antes',
            field=models.CharField(blank=True, help_text='Estado operativo del vehículo antes de la OT', max_length=30),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado_operativo_despues',
            field=models.CharField(blank=True, help_text='Estado operativo del vehículo después de la OT', max_length=30),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_limite_sla',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para cumplir SLA', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='site',
            field=models.CharField(blank=True, help_text='Site o ubicación operativa donde se realiza la OT', max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='sla_vencido',
            field=models.BooleanField(default=False, help_text='Indica si la OT excedió el tiempo límite (SLA)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tiempo_ejecucion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo total en ejecución (horas)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tiempo_espera',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo en espera antes de iniciar trabajo (horas)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tiempo_total_reparacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo total de reparación (días)', max_digits=10, null=True),
        ),
    ]
