# Generated by Django 5.2.8 on 2025-11-19 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0009_ordentrabajo_backup_ordentrabajo_causa_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='ot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='workorders.ordentrabajo'),
        ),
    ]
