# Generated by Django 5.2.8 on 2025-11-19 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('workorders', '0010_make_evidencia_ot_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='chofer',
            field=models.ForeignKey(blank=True, help_text='Chofer que ingresa el vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_creadas', to='drivers.chofer'),
        ),
    ]
