# Generated by Django 5.2.8 on 2025-11-19 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_ingresovehiculo_fecha_salida_and_more'),
        ('workorders', '0011_add_chofer_to_ordentrabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='invalidado',
            field=models.BooleanField(default=False, help_text='Indica si la evidencia fue invalidada'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='invalidado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='invalidado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_invalidadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='motivo_invalidacion',
            field=models.TextField(blank=True, help_text='Motivo de invalidación'),
        ),
        migrations.CreateModel(
            name='BloqueoVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('DOCUMENTACION_INCOMPLETA', 'Documentación Incompleta'), ('SANCION', 'Sanción'), ('MANTENIMIENTO_OBLIGATORIO', 'Mantenimiento Obligatorio'), ('OTRO', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_creados', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_resueltos', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='vehicles.vehiculo')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['vehiculo', 'estado'], name='workorders__vehicul_492cf9_idx'), models.Index(fields=['estado', 'creado_en'], name='workorders__estado_d9e771_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComentarioOT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('menciones', models.JSONField(blank=True, default=list)),
                ('editado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('editado_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='workorders.comentarioot')),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='workorders.ordentrabajo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_ot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_en'],
                'indexes': [models.Index(fields=['ot', 'creado_en'], name='workorders__ot_id_205c52_idx'), models.Index(fields=['usuario', 'creado_en'], name='workorders__usuario_234602_idx')],
            },
        ),
        migrations.CreateModel(
            name='VersionEvidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_anterior', models.URLField()),
                ('motivo', models.TextField()),
                ('invalidado_en', models.DateTimeField(auto_now_add=True)),
                ('evidencia_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='workorders.evidencia')),
                ('invalidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invalidado_en'],
                'indexes': [models.Index(fields=['evidencia_original', 'invalidado_en'], name='workorders__evidenc_25c55f_idx')],
            },
        ),
    ]
