# Generated by Django 5.2.8 on 2025-11-20 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0012_evidencia_invalidado_evidencia_invalidado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='subido_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que subió esta evidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
