# Generated by Django 5.2.7 on 2025-10-16 02:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=32, unique=True)),
                ('marca', models.CharField(blank=True, max_length=64)),
                ('modelo', models.CharField(blank=True, max_length=64)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('EN_MANTENIMIENTO', 'EN_MANTENIMIENTO'), ('BAJA', 'BAJA')], default='ACTIVO', max_length=32)),
            ],
        ),
    ]
