# Generated by Django 5.2.7 on 2025-10-16 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['estado'], name='vehicles_ve_estado_707e75_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['marca', 'modelo'], name='vehicles_ve_marca_45cd2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.CheckConstraint(condition=models.Q(('anio__isnull', True), models.Q(('anio__gte', 1900), ('anio__lte', 2100)), _connector='OR'), name='vehiculo_anio_valid'),
        ),
    ]
