# Generated by Django 5.2.7 on 2025-11-17 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiculo_created_at_vehiculo_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('EN_ESPERA', 'EN_ESPERA'), ('EN_MANTENIMIENTO', 'EN_MANTENIMIENTO'), ('BAJA', 'BAJA')], default='ACTIVO', max_length=32),
        ),
        migrations.CreateModel(
            name='IngresoVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='vehicles.vehiculo')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaIngreso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('tipo', models.CharField(choices=[('FOTO_INGRESO', 'Foto de Ingreso'), ('FOTO_DANOS', 'Foto de Daños'), ('FOTO_DOCUMENTOS', 'Foto de Documentos'), ('OTRO', 'Otro')], default='FOTO_INGRESO', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='vehicles.ingresovehiculo')),
            ],
        ),
        migrations.AddIndex(
            model_name='ingresovehiculo',
            index=models.Index(fields=['fecha_ingreso'], name='vehicles_in_fecha_i_2d9cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresovehiculo',
            index=models.Index(fields=['vehiculo', 'fecha_ingreso'], name='vehicles_in_vehicul_109199_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciaingreso',
            index=models.Index(fields=['ingreso', 'tipo'], name='vehicles_ev_ingreso_a28754_idx'),
        ),
    ]
