# Generated by Django 5.2.7 on 2025-11-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehiculo_estado_ingresovehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(blank=True, choices=[('REPARTO', 'Reparto'), ('VENTAS', 'Ventas'), ('RESPALDO', 'Respaldo')], help_text='Categoría operativa', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='km_mensual_promedio',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje promedio mensual', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='sucursal',
            field=models.CharField(blank=True, help_text='Sucursal específica', max_length=100),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ELECTRICO', 'Eléctrico'), ('DIESEL', 'Diésel'), ('UTILITARIO', 'Utilitario'), ('REPARTO', 'Reparto'), ('VENTAS', 'Ventas'), ('RESPALDO', 'Respaldo')], help_text='Tipo de vehículo (eléctrico/diésel/utilitario)', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='zona',
            field=models.CharField(blank=True, help_text='Zona o sucursal asignada', max_length=100),
        ),
    ]
