# Generated by Django 5.2.7 on 2025-11-18 05:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehiculo_categoria_vehiculo_km_mensual_promedio_and_more'),
        ('workorders', '0008_alter_evidencia_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='ceco',
            field=models.CharField(blank=True, help_text='Centro de Costo (CeCo)', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cumplimiento',
            field=models.CharField(choices=[('EN_POLITICA', 'En Política'), ('FUERA_POLITICA', 'Fuera de Política')], default='EN_POLITICA', help_text='Cumplimiento de política', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='equipo_sap',
            field=models.CharField(blank=True, help_text='Equipo SAP', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado_operativo',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('EN_TALLER', 'En Taller'), ('BLOQUEADO', 'Bloqueado/TCT'), ('FUERA_POLITICA', 'Fuera de Política'), ('REVISION_VENCIDA', 'Revisión Vencida'), ('SIN_MOVIMIENTO', 'Sin Movimiento')], default='OPERATIVO', help_text='Estado operativo del vehículo', max_length=30),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje actual del vehículo', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='proxima_revision',
            field=models.DateField(blank=True, help_text='Fecha de próxima revisión', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='site',
            field=models.CharField(blank=True, help_text='Site o ubicación operativa', max_length=100),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor asignado al vehículo', limit_choices_to={'rol__in': ['SUPERVISOR', 'COORDINADOR_ZONA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_supervisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tct',
            field=models.BooleanField(default=False, help_text='Bloqueo Temporal (TCT) activo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tct_dias',
            field=models.PositiveIntegerField(default=0, help_text='Días con TCT activo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tct_fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha de inicio del bloqueo TCT', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ultima_revision',
            field=models.DateField(blank=True, help_text='Fecha de última revisión', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ultimo_movimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha de último movimiento registrado', null=True),
        ),
        migrations.CreateModel(
            name='BackupVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('duracion_dias', models.DecimalField(blank=True, decimal_places=2, help_text='Duración del uso del backup (días)', max_digits=10, null=True)),
                ('motivo', models.TextField()),
                ('site', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'En Uso'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='workorders.ordentrabajo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_asignados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo_backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backups_asignados', to='vehicles.vehiculo')),
                ('vehiculo_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backups_recibidos', to='vehicles.vehiculo')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('OT_CREADA', 'OT Creada'), ('OT_CERRADA', 'OT Cerrada'), ('OT_EN_QA', 'OT en QA'), ('OT_RECHAZADA', 'OT Rechazada'), ('INGRESO_TALLER', 'Ingreso a Taller'), ('SALIDA_TALLER', 'Salida de Taller'), ('BACKUP_ASIGNADO', 'Backup Asignado'), ('BACKUP_DEVUELTO', 'Backup Devuelto'), ('FALLA_REGISTRADA', 'Falla Registrada'), ('MANTENIMIENTO', 'Mantenimiento'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('tiempo_permanencia', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo de permanencia en taller (días)', max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('falla', models.CharField(blank=True, max_length=200)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('estado_antes', models.CharField(blank=True, max_length=30)),
                ('estado_despues', models.CharField(blank=True, max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('backup_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_historial', to='vehicles.backupvehiculo')),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_vehiculo', to='workorders.ordentrabajo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_historial', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='vehicles.vehiculo')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='backupvehiculo',
            index=models.Index(fields=['vehiculo_principal', 'estado'], name='vehicles_ba_vehicul_30607d_idx'),
        ),
        migrations.AddIndex(
            model_name='backupvehiculo',
            index=models.Index(fields=['vehiculo_backup', 'estado'], name='vehicles_ba_vehicul_e1ca30_idx'),
        ),
        migrations.AddIndex(
            model_name='backupvehiculo',
            index=models.Index(fields=['fecha_inicio'], name='vehicles_ba_fecha_i_d4900a_idx'),
        ),
        migrations.AddIndex(
            model_name='historialvehiculo',
            index=models.Index(fields=['vehiculo', 'creado_en'], name='vehicles_hi_vehicul_e82fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='historialvehiculo',
            index=models.Index(fields=['tipo_evento', 'creado_en'], name='vehicles_hi_tipo_ev_fd642c_idx'),
        ),
    ]
