# Generated by Django 5.2.8 on 2025-11-19 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehiculo_ceco_vehiculo_cumplimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresovehiculo',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingresovehiculo',
            name='guardia_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresovehiculo',
            name='kilometraje_salida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingresovehiculo',
            name='observaciones_salida',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingresovehiculo',
            name='salio',
            field=models.BooleanField(default=False),
        ),
    ]
