# Generated by Django 5.2.7 on 2025-11-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('GUARDIA', 'Guardia'), ('MECANICO', 'Mecánico'), ('SUPERVISOR', 'Supervisor Zonal'), ('RECEPCIONISTA', 'Recepcionista'), ('JEFE_TALLER', 'Jefe de Taller'), ('EJECUTIVO', 'Ejecutivo'), ('SPONSOR', 'Sponsor'), ('ADMIN', 'Administrador')], default='ADMIN', max_length=20),
        ),
    ]
