# Generated by Django 5.2.7 on 2025-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT sin puntos ni guión (ej: 123456789)', max_length=12, null=True, unique=True),
        ),
    ]
