# Generated by Django 5.2.7 on 2025-11-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('GUARDIA', 'Guardia'), ('MECANICO', 'Mecánico'), ('SUPERVISOR', 'Supervisor Zonal'), ('COORDINADOR_ZONA', 'Coordinador de Zona'), ('RECEPCIONISTA', 'Recepcionista'), ('JEFE_TALLER', 'Jefe de Taller'), ('EJECUTIVO', 'Ejecutivo'), ('SPONSOR', 'Sponsor'), ('ADMIN', 'Administrador'), ('CHOFER', 'Chofer')], default='ADMIN', max_length=20),
        ),
    ]
