# Generated by Django 5.2.7 on 2025-11-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notificaciones_email',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones por email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notificaciones_push',
            field=models.BooleanField(default=False, help_text='Recibir notificaciones push del navegador'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notificaciones_sonido',
            field=models.BooleanField(default=True, help_text='Reproducir sonido al recibir notificaciones'),
        ),
    ]
