# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_notificaciones_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text='Si está marcado, este usuario no se puede eliminar, solo editar y ver'),
        ),
    ]

