# Generated by Django 5.2.7 on 2025-11-17 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0003_alter_vehiculo_estado_ingresovehiculo_and_more'),
        ('workorders', '0006_ordentrabajo_prioridad_ordentrabajo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=128)),
                ('categoria', models.CharField(blank=True, max_length=128)),
                ('precio_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidad_medida', models.CharField(default='UNIDAD', max_length=32)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='inventory_r_codigo_522d7b_idx'), models.Index(fields=['categoria', 'activo'], name='inventory_r_categor_c569ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_anterior', models.PositiveIntegerField()),
                ('cantidad_nueva', models.PositiveIntegerField()),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('item_ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='workorders.itemot')),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='workorders.ordentrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='vehicles.vehiculo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.repuesto')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='inventory_m_fecha_867d0f_idx'), models.Index(fields=['repuesto', 'fecha'], name='inventory_m_repuest_c6decf_idx'), models.Index(fields=['tipo', 'fecha'], name='inventory_m_tipo_31b222_idx'), models.Index(fields=['ot', 'vehiculo'], name='inventory_m_ot_id_587757_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialRepuestoVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('item_ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_repuestos', to='workorders.itemot')),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_repuestos', to='workorders.ordentrabajo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_repuestos', to='vehicles.vehiculo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_vehiculos', to='inventory.repuesto')),
            ],
            options={
                'ordering': ['-fecha_uso'],
                'indexes': [models.Index(fields=['vehiculo', 'fecha_uso'], name='inventory_h_vehicul_076e14_idx'), models.Index(fields=['repuesto', 'fecha_uso'], name='inventory_h_repuest_12fb1b_idx'), models.Index(fields=['ot'], name='inventory_h_ot_id_bf6be8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolicitudRepuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_entregada', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_entregadas', to=settings.AUTH_USER_MODEL)),
                ('item_ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='workorders.itemot')),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_repuestos', to='workorders.ordentrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='inventory.repuesto')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['estado', 'fecha_solicitud'], name='inventory_s_estado_5b5e2b_idx'), models.Index(fields=['ot', 'estado'], name='inventory_s_ot_id_7ef144_idx'), models.Index(fields=['repuesto', 'estado'], name='inventory_s_repuest_936160_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.PositiveIntegerField(default=0)),
                ('cantidad_minima', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repuesto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.repuesto')),
            ],
            options={
                'indexes': [models.Index(fields=['cantidad_actual'], name='inventory_s_cantida_3c062e_idx')],
            },
        ),
    ]
