# Generated by Django 5.2.7 on 2025-11-18 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0004_vehiculo_categoria_vehiculo_km_mensual_promedio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rut', models.CharField(db_index=True, help_text='RUT sin puntos ni guión', max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('zona', models.CharField(blank=True, help_text='Zona o sucursal asignada', max_length=100)),
                ('sucursal', models.CharField(blank=True, help_text='Sucursal específica', max_length=100)),
                ('km_mensual_promedio', models.PositiveIntegerField(blank=True, help_text='Kilometraje promedio mensual', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehiculo_asignado', models.ForeignKey(blank=True, help_text='Vehículo actualmente asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choferes', to='vehicles.vehiculo')),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAsignacionVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo_fin', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='drivers.chofer')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_choferes', to='vehicles.vehiculo')),
            ],
            options={
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddIndex(
            model_name='chofer',
            index=models.Index(fields=['rut'], name='drivers_cho_rut_726c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='chofer',
            index=models.Index(fields=['zona', 'activo'], name='drivers_cho_zona_8c4223_idx'),
        ),
        migrations.AddIndex(
            model_name='chofer',
            index=models.Index(fields=['vehiculo_asignado'], name='drivers_cho_vehicul_7bd6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='historialasignacionvehiculo',
            index=models.Index(fields=['chofer', 'activa'], name='drivers_his_chofer__4889bd_idx'),
        ),
        migrations.AddIndex(
            model_name='historialasignacionvehiculo',
            index=models.Index(fields=['vehiculo', 'activa'], name='drivers_his_vehicul_b472bb_idx'),
        ),
        migrations.AddIndex(
            model_name='historialasignacionvehiculo',
            index=models.Index(fields=['fecha_asignacion'], name='drivers_his_fecha_a_fa1c55_idx'),
        ),
    ]
