# Generated by Django 5.2.7 on 2025-11-18 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0004_vehiculo_categoria_vehiculo_km_mensual_promedio_and_more'),
        ('workorders', '0007_alter_pausa_options_ordentrabajo_diagnostico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True, unique=True)),
                ('cupos_totales', models.PositiveIntegerField(default=10, help_text='Cupos totales del día')),
                ('cupos_ocupados', models.PositiveIntegerField(default=0)),
                ('zona', models.CharField(blank=True, help_text='Zona específica (opcional)', max_length=100)),
            ],
            options={
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['fecha', 'zona'], name='scheduling__fecha_aa77d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_programada', models.DateTimeField(help_text='Fecha y hora programada para el mantenimiento')),
                ('motivo', models.TextField(help_text='Motivo de la programación')),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('EMERGENCIA', 'Emergencia')], default='PREVENTIVO', max_length=50)),
                ('zona', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada')], default='PROGRAMADA', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinador', models.ForeignKey(limit_choices_to={'rol': 'COORDINADOR_ZONA'}, on_delete=django.db.models.deletion.PROTECT, related_name='agendas_creadas', to=settings.AUTH_USER_MODEL)),
                ('ot_asociada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_origen', to='workorders.ordentrabajo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas', to='vehicles.vehiculo')),
            ],
            options={
                'ordering': ['fecha_programada'],
                'indexes': [models.Index(fields=['fecha_programada'], name='scheduling__fecha_p_e6e3aa_idx'), models.Index(fields=['estado', 'fecha_programada'], name='scheduling__estado_fcfb41_idx'), models.Index(fields=['vehiculo', 'estado'], name='scheduling__vehicul_57bd6c_idx'), models.Index(fields=['zona', 'fecha_programada'], name='scheduling__zona_32be82_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado__in', ['PROGRAMADA', 'CONFIRMADA', 'EN_PROCESO'])), fields=('vehiculo', 'fecha_programada'), name='unique_vehiculo_fecha_activa')],
            },
        ),
    ]
