# Generated by Django 5.2.7 on 2025-11-18 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0004_vehiculo_categoria_vehiculo_km_mensual_promedio_and_more'),
        ('workorders', '0007_alter_pausa_options_ordentrabajo_diagnostico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergenciaRuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Descripción de la emergencia')),
                ('ubicacion', models.CharField(help_text='Ubicación donde ocurrió la emergencia', max_length=255)),
                ('zona', models.CharField(blank=True, max_length=100)),
                ('prioridad', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media')], default='ALTA', max_length=20)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('APROBADA', 'Aprobada'), ('ASIGNADA', 'Asignada'), ('EN_CAMINO', 'En Camino'), ('EN_REPARACION', 'En Reparación'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada'), ('RECHAZADA', 'Rechazada')], default='SOLICITADA', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobador', models.ForeignKey(blank=True, help_text='Jefe de Taller o Subgerencia que aprueba', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('mecanico_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'MECANICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_atendidas', to=settings.AUTH_USER_MODEL)),
                ('ot_asociada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencia_origen', to='workorders.ordentrabajo')),
                ('solicitante', models.ForeignKey(help_text='Coordinador o Supervisor que solicita', on_delete=django.db.models.deletion.PROTECT, related_name='emergencias_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('supervisor_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['SUPERVISOR', 'COORDINADOR_ZONA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_supervisadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergencias', to='vehicles.vehiculo')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['estado', 'fecha_solicitud'], name='emergencies_estado_6bbee0_idx'), models.Index(fields=['vehiculo', 'estado'], name='emergencies_vehicul_123b59_idx'), models.Index(fields=['zona', 'estado'], name='emergencies_zona_73dcea_idx'), models.Index(fields=['mecanico_asignado', 'estado'], name='emergencies_mecanic_23a3a9_idx')],
            },
        ),
    ]
