--
-- PostgreSQL database dump
--

\restrict RfUTt0lkB8sjFb6mNBjm319lO5RV79LKbaAtAZXjdMCHPbwyO3KhvokS7kV6V8A

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: drivers_chofer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drivers_chofer (
    id uuid NOT NULL,
    nombre_completo character varying(255) NOT NULL,
    rut character varying(12) NOT NULL,
    telefono character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    zona character varying(100) NOT NULL,
    sucursal character varying(100) NOT NULL,
    km_mensual_promedio integer,
    activo boolean NOT NULL,
    fecha_ingreso date,
    observaciones text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    vehiculo_asignado_id uuid,
    CONSTRAINT drivers_chofer_km_mensual_promedio_check CHECK ((km_mensual_promedio >= 0))
);


--
-- Name: drivers_historialasignacionvehiculo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drivers_historialasignacionvehiculo (
    id uuid NOT NULL,
    fecha_asignacion timestamp with time zone NOT NULL,
    fecha_fin timestamp with time zone,
    motivo_fin text NOT NULL,
    activa boolean NOT NULL,
    chofer_id uuid NOT NULL,
    vehiculo_id uuid NOT NULL
);


--
-- Name: emergencies_emergenciaruta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emergencies_emergenciaruta (
    id uuid NOT NULL,
    descripcion text NOT NULL,
    ubicacion character varying(255) NOT NULL,
    zona character varying(100) NOT NULL,
    prioridad character varying(20) NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_solicitud timestamp with time zone NOT NULL,
    fecha_aprobacion timestamp with time zone,
    fecha_asignacion timestamp with time zone,
    fecha_resolucion timestamp with time zone,
    fecha_cierre timestamp with time zone,
    observaciones text NOT NULL,
    aprobador_id bigint,
    mecanico_asignado_id bigint,
    ot_asociada_id uuid,
    solicitante_id bigint NOT NULL,
    supervisor_asignado_id bigint,
    vehiculo_id uuid NOT NULL
);


--
-- Name: inventory_historialrepuestovehiculo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_historialrepuestovehiculo (
    id uuid NOT NULL,
    cantidad integer NOT NULL,
    fecha_uso timestamp with time zone NOT NULL,
    costo_unitario numeric(12,2),
    item_ot_id uuid,
    ot_id uuid,
    vehiculo_id uuid NOT NULL,
    repuesto_id uuid NOT NULL,
    CONSTRAINT inventory_historialrepuestovehiculo_cantidad_check CHECK ((cantidad >= 0))
);


--
-- Name: inventory_movimientostock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_movimientostock (
    id uuid NOT NULL,
    tipo character varying(20) NOT NULL,
    cantidad integer NOT NULL,
    cantidad_anterior integer NOT NULL,
    cantidad_nueva integer NOT NULL,
    motivo text NOT NULL,
    fecha timestamp with time zone NOT NULL,
    item_ot_id uuid,
    ot_id uuid,
    usuario_id bigint NOT NULL,
    vehiculo_id uuid,
    repuesto_id uuid NOT NULL,
    CONSTRAINT inventory_movimientostock_cantidad_anterior_check CHECK ((cantidad_anterior >= 0)),
    CONSTRAINT inventory_movimientostock_cantidad_check CHECK ((cantidad >= 0)),
    CONSTRAINT inventory_movimientostock_cantidad_nueva_check CHECK ((cantidad_nueva >= 0))
);


--
-- Name: inventory_repuesto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_repuesto (
    id uuid NOT NULL,
    codigo character varying(64) NOT NULL,
    nombre character varying(255) NOT NULL,
    descripcion text NOT NULL,
    marca character varying(128) NOT NULL,
    categoria character varying(128) NOT NULL,
    precio_referencia numeric(12,2),
    unidad_medida character varying(32) NOT NULL,
    activo boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: inventory_solicitudrepuesto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_solicitudrepuesto (
    id uuid NOT NULL,
    cantidad_solicitada integer NOT NULL,
    cantidad_entregada integer NOT NULL,
    estado character varying(20) NOT NULL,
    motivo text NOT NULL,
    fecha_solicitud timestamp with time zone NOT NULL,
    fecha_aprobacion timestamp with time zone,
    fecha_entrega timestamp with time zone,
    aprobador_id bigint,
    entregador_id bigint,
    item_ot_id uuid,
    ot_id uuid NOT NULL,
    repuesto_id uuid NOT NULL,
    solicitante_id bigint,
    CONSTRAINT inventory_solicitudrepuesto_cantidad_entregada_check CHECK ((cantidad_entregada >= 0)),
    CONSTRAINT inventory_solicitudrepuesto_cantidad_solicitada_check CHECK ((cantidad_solicitada >= 0))
);


--
-- Name: inventory_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_stock (
    id bigint NOT NULL,
    cantidad_actual integer NOT NULL,
    cantidad_minima integer NOT NULL,
    ubicacion character varying(128) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    repuesto_id uuid NOT NULL,
    CONSTRAINT inventory_stock_cantidad_actual_check CHECK ((cantidad_actual >= 0)),
    CONSTRAINT inventory_stock_cantidad_minima_check CHECK ((cantidad_minima >= 0))
);


--
-- Name: inventory_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications_notification (
    id uuid NOT NULL,
    tipo character varying(20) NOT NULL,
    titulo character varying(200) NOT NULL,
    mensaje text NOT NULL,
    estado character varying(15) NOT NULL,
    creada_en timestamp with time zone NOT NULL,
    leida_en timestamp with time zone,
    metadata jsonb NOT NULL,
    evidencia_id uuid,
    ot_id uuid,
    usuario_id bigint NOT NULL
);


--
-- Name: scheduling_agenda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scheduling_agenda (
    id uuid NOT NULL,
    fecha_programada timestamp with time zone NOT NULL,
    motivo text NOT NULL,
    tipo_mantenimiento character varying(50) NOT NULL,
    zona character varying(100) NOT NULL,
    estado character varying(20) NOT NULL,
    observaciones text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    coordinador_id bigint NOT NULL,
    ot_asociada_id uuid,
    vehiculo_id uuid NOT NULL
);


--
-- Name: scheduling_cupodiario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scheduling_cupodiario (
    id uuid NOT NULL,
    fecha date NOT NULL,
    cupos_totales integer NOT NULL,
    cupos_ocupados integer NOT NULL,
    zona character varying(100) NOT NULL,
    CONSTRAINT scheduling_cupodiario_cupos_ocupados_check CHECK ((cupos_ocupados >= 0)),
    CONSTRAINT scheduling_cupodiario_cupos_totales_check CHECK ((cupos_totales >= 0))
);


--
-- Name: users_passwordresettoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_passwordresettoken (
    id uuid NOT NULL,
    token character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: users_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_profile (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    user_id bigint NOT NULL,
    phone_number character varying(32) NOT NULL,
    notificaciones_email boolean NOT NULL,
    notificaciones_push boolean NOT NULL,
    notificaciones_sonido boolean NOT NULL
);


--
-- Name: users_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    rol character varying(20) NOT NULL,
    rut character varying(12),
    is_permanent boolean NOT NULL
);


--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_groups (
    id integer NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_user_permissions (
    id integer NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicles_backupvehiculo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicles_backupvehiculo (
    id uuid NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_devolucion timestamp with time zone,
    duracion_dias numeric(10,2),
    motivo text NOT NULL,
    site character varying(100) NOT NULL,
    estado character varying(20) NOT NULL,
    observaciones text NOT NULL,
    creado_en timestamp with time zone NOT NULL,
    actualizado_en timestamp with time zone NOT NULL,
    ot_id uuid,
    supervisor_id bigint,
    vehiculo_backup_id uuid NOT NULL,
    vehiculo_principal_id uuid NOT NULL
);


--
-- Name: vehicles_evidenciaingreso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicles_evidenciaingreso (
    id uuid NOT NULL,
    url character varying(200) NOT NULL,
    tipo character varying(20) NOT NULL,
    descripcion text NOT NULL,
    subido_en timestamp with time zone NOT NULL,
    ingreso_id uuid NOT NULL
);


--
-- Name: vehicles_historialvehiculo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicles_historialvehiculo (
    id uuid NOT NULL,
    tipo_evento character varying(30) NOT NULL,
    fecha_ingreso timestamp with time zone,
    fecha_salida timestamp with time zone,
    tiempo_permanencia numeric(10,2),
    descripcion text NOT NULL,
    falla character varying(200) NOT NULL,
    site character varying(100) NOT NULL,
    estado_antes character varying(30) NOT NULL,
    estado_despues character varying(30) NOT NULL,
    creado_en timestamp with time zone NOT NULL,
    backup_utilizado_id uuid,
    ot_id uuid,
    supervisor_id bigint,
    vehiculo_id uuid NOT NULL
);


--
-- Name: vehicles_ingresovehiculo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicles_ingresovehiculo (
    id uuid NOT NULL,
    fecha_ingreso timestamp with time zone NOT NULL,
    observaciones text NOT NULL,
    kilometraje integer,
    qr_code character varying(255) NOT NULL,
    guardia_id bigint NOT NULL,
    vehiculo_id uuid NOT NULL,
    fecha_salida timestamp with time zone,
    guardia_salida_id bigint,
    kilometraje_salida integer,
    observaciones_salida text NOT NULL,
    salio boolean NOT NULL,
    CONSTRAINT vehicles_ingresovehiculo_kilometraje_check CHECK ((kilometraje >= 0)),
    CONSTRAINT vehicles_ingresovehiculo_kilometraje_salida_check CHECK ((kilometraje_salida >= 0))
);


--
-- Name: vehicles_vehiculo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicles_vehiculo (
    id uuid NOT NULL,
    patente character varying(32) NOT NULL,
    marca character varying(64) NOT NULL,
    modelo character varying(64) NOT NULL,
    anio integer,
    vin character varying(64) NOT NULL,
    estado character varying(32) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    categoria character varying(20) NOT NULL,
    km_mensual_promedio integer,
    sucursal character varying(100) NOT NULL,
    tipo character varying(20) NOT NULL,
    zona character varying(100) NOT NULL,
    ceco character varying(50) NOT NULL,
    cumplimiento character varying(20) NOT NULL,
    equipo_sap character varying(50) NOT NULL,
    estado_operativo character varying(30) NOT NULL,
    kilometraje_actual integer,
    proxima_revision date,
    site character varying(100) NOT NULL,
    supervisor_id bigint,
    tct boolean NOT NULL,
    tct_dias integer NOT NULL,
    tct_fecha_inicio timestamp with time zone,
    ultima_revision date,
    ultimo_movimiento timestamp with time zone,
    CONSTRAINT vehicles_vehiculo_anio_check CHECK ((anio >= 0)),
    CONSTRAINT vehicles_vehiculo_kilometraje_actual_check CHECK ((kilometraje_actual >= 0)),
    CONSTRAINT vehicles_vehiculo_km_mensual_promedio_check CHECK ((km_mensual_promedio >= 0)),
    CONSTRAINT vehicles_vehiculo_tct_dias_check CHECK ((tct_dias >= 0)),
    CONSTRAINT vehiculo_anio_valid CHECK (((anio IS NULL) OR ((anio >= 1900) AND (anio <= 2100))))
);


--
-- Name: workorders_aprobacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_aprobacion (
    id uuid NOT NULL,
    estado character varying(20) NOT NULL,
    comentario text NOT NULL,
    fecha timestamp with time zone NOT NULL,
    sponsor_id bigint NOT NULL,
    presupuesto_id uuid NOT NULL
);


--
-- Name: workorders_auditoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_auditoria (
    id bigint NOT NULL,
    accion character varying(64) NOT NULL,
    objeto_tipo character varying(64) NOT NULL,
    objeto_id character varying(64) NOT NULL,
    payload jsonb NOT NULL,
    ts timestamp with time zone NOT NULL,
    usuario_id bigint
);


--
-- Name: workorders_auditoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workorders_auditoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workorders_auditoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workorders_bloqueovehiculo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_bloqueovehiculo (
    id uuid NOT NULL,
    tipo character varying(50) NOT NULL,
    estado character varying(20) NOT NULL,
    motivo text NOT NULL,
    creado_en timestamp with time zone NOT NULL,
    resuelto_en timestamp with time zone,
    creado_por_id bigint,
    resuelto_por_id bigint,
    vehiculo_id uuid NOT NULL
);


--
-- Name: workorders_checklist; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_checklist (
    id uuid NOT NULL,
    resultado character varying(10) NOT NULL,
    observaciones text NOT NULL,
    fecha timestamp with time zone NOT NULL,
    verificador_id bigint,
    ot_id uuid NOT NULL
);


--
-- Name: workorders_comentarioot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_comentarioot (
    id uuid NOT NULL,
    contenido text NOT NULL,
    menciones jsonb NOT NULL,
    editado boolean NOT NULL,
    creado_en timestamp with time zone NOT NULL,
    editado_en timestamp with time zone,
    comentario_padre_id uuid,
    ot_id uuid NOT NULL,
    usuario_id bigint
);


--
-- Name: workorders_detallepresup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_detallepresup (
    id uuid NOT NULL,
    concepto character varying(255) NOT NULL,
    cantidad integer NOT NULL,
    precio numeric(12,2) NOT NULL,
    presupuesto_id uuid NOT NULL,
    CONSTRAINT workorders_detallepresup_cantidad_check CHECK ((cantidad >= 0))
);


--
-- Name: workorders_evidencia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_evidencia (
    id uuid NOT NULL,
    url character varying(200) NOT NULL,
    tipo character varying(15) NOT NULL,
    subido_en timestamp with time zone NOT NULL,
    ot_id uuid,
    descripcion text NOT NULL,
    invalidado boolean NOT NULL,
    invalidado_en timestamp with time zone,
    invalidado_por_id bigint,
    motivo_invalidacion text NOT NULL,
    subido_por_id bigint
);


--
-- Name: workorders_itemot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_itemot (
    id uuid NOT NULL,
    tipo character varying(20) NOT NULL,
    descripcion text NOT NULL,
    cantidad integer NOT NULL,
    costo_unitario numeric(12,2) NOT NULL,
    ot_id uuid NOT NULL,
    CONSTRAINT itemot_cantidad_gt_0 CHECK ((cantidad > 0)),
    CONSTRAINT itemot_costo_gte_0 CHECK ((costo_unitario >= (0)::numeric)),
    CONSTRAINT workorders_itemot_cantidad_check CHECK ((cantidad >= 0))
);


--
-- Name: workorders_ordentrabajo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_ordentrabajo (
    id uuid NOT NULL,
    estado character varying(20) NOT NULL,
    motivo text NOT NULL,
    apertura timestamp with time zone NOT NULL,
    cierre timestamp with time zone,
    responsable_id bigint,
    vehiculo_id uuid NOT NULL,
    prioridad character varying(20) NOT NULL,
    tipo character varying(50) NOT NULL,
    diagnostico text NOT NULL,
    fecha_aprobacion_supervisor timestamp with time zone,
    fecha_asignacion_mecanico timestamp with time zone,
    fecha_diagnostico timestamp with time zone,
    fecha_inicio_ejecucion timestamp with time zone,
    jefe_taller_id bigint,
    mecanico_id bigint,
    supervisor_id bigint,
    zona character varying(100) NOT NULL,
    backup_id uuid,
    causa_ingreso text NOT NULL,
    causa_salida text NOT NULL,
    estado_operativo_antes character varying(30) NOT NULL,
    estado_operativo_despues character varying(30) NOT NULL,
    fecha_limite_sla timestamp with time zone,
    site character varying(100) NOT NULL,
    sla_vencido boolean NOT NULL,
    tiempo_ejecucion numeric(10,2),
    tiempo_espera numeric(10,2),
    tiempo_total_reparacion numeric(10,2),
    chofer_id uuid
);


--
-- Name: workorders_pausa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_pausa (
    id uuid NOT NULL,
    motivo character varying(255) NOT NULL,
    inicio timestamp with time zone NOT NULL,
    fin timestamp with time zone,
    ot_id uuid NOT NULL,
    usuario_id bigint NOT NULL,
    es_automatica boolean NOT NULL,
    tipo character varying(30) NOT NULL
);


--
-- Name: workorders_presupuesto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_presupuesto (
    id uuid NOT NULL,
    total numeric(14,2) NOT NULL,
    requiere_aprobacion boolean NOT NULL,
    umbral numeric(14,2),
    creado_en timestamp with time zone NOT NULL,
    ot_id uuid NOT NULL
);


--
-- Name: workorders_versionevidencia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workorders_versionevidencia (
    id uuid NOT NULL,
    url_anterior character varying(200) NOT NULL,
    motivo text NOT NULL,
    invalidado_en timestamp with time zone NOT NULL,
    evidencia_original_id uuid NOT NULL,
    invalidado_por_id bigint
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: drivers_chofer drivers_chofer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers_chofer
    ADD CONSTRAINT drivers_chofer_pkey PRIMARY KEY (id);


--
-- Name: drivers_chofer drivers_chofer_rut_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers_chofer
    ADD CONSTRAINT drivers_chofer_rut_key UNIQUE (rut);


--
-- Name: drivers_historialasignacionvehiculo drivers_historialasignacionvehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers_historialasignacionvehiculo
    ADD CONSTRAINT drivers_historialasignacionvehiculo_pkey PRIMARY KEY (id);


--
-- Name: emergencies_emergenciaruta emergencies_emergenciaruta_ot_asociada_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emergencies_emergenciaruta
    ADD CONSTRAINT emergencies_emergenciaruta_ot_asociada_id_key UNIQUE (ot_asociada_id);


--
-- Name: emergencies_emergenciaruta emergencies_emergenciaruta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emergencies_emergenciaruta
    ADD CONSTRAINT emergencies_emergenciaruta_pkey PRIMARY KEY (id);


--
-- Name: inventory_historialrepuestovehiculo inventory_historialrepuestovehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_historialrepuestovehiculo
    ADD CONSTRAINT inventory_historialrepuestovehiculo_pkey PRIMARY KEY (id);


--
-- Name: inventory_movimientostock inventory_movimientostock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_movimientostock
    ADD CONSTRAINT inventory_movimientostock_pkey PRIMARY KEY (id);


--
-- Name: inventory_repuesto inventory_repuesto_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_repuesto
    ADD CONSTRAINT inventory_repuesto_codigo_key UNIQUE (codigo);


--
-- Name: inventory_repuesto inventory_repuesto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_repuesto
    ADD CONSTRAINT inventory_repuesto_pkey PRIMARY KEY (id);


--
-- Name: inventory_solicitudrepuesto inventory_solicitudrepuesto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_solicitudrepuesto
    ADD CONSTRAINT inventory_solicitudrepuesto_pkey PRIMARY KEY (id);


--
-- Name: inventory_stock inventory_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stock
    ADD CONSTRAINT inventory_stock_pkey PRIMARY KEY (id);


--
-- Name: inventory_stock inventory_stock_repuesto_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stock
    ADD CONSTRAINT inventory_stock_repuesto_id_key UNIQUE (repuesto_id);


--
-- Name: notifications_notification notifications_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_pkey PRIMARY KEY (id);


--
-- Name: scheduling_agenda scheduling_agenda_ot_asociada_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_agenda
    ADD CONSTRAINT scheduling_agenda_ot_asociada_id_key UNIQUE (ot_asociada_id);


--
-- Name: scheduling_agenda scheduling_agenda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_agenda
    ADD CONSTRAINT scheduling_agenda_pkey PRIMARY KEY (id);


--
-- Name: scheduling_cupodiario scheduling_cupodiario_fecha_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_cupodiario
    ADD CONSTRAINT scheduling_cupodiario_fecha_key UNIQUE (fecha);


--
-- Name: scheduling_cupodiario scheduling_cupodiario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_cupodiario
    ADD CONSTRAINT scheduling_cupodiario_pkey PRIMARY KEY (id);


--
-- Name: users_passwordresettoken users_passwordresettoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_passwordresettoken
    ADD CONSTRAINT users_passwordresettoken_pkey PRIMARY KEY (id);


--
-- Name: users_passwordresettoken users_passwordresettoken_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_passwordresettoken
    ADD CONSTRAINT users_passwordresettoken_token_key UNIQUE (token);


--
-- Name: users_profile users_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_pkey PRIMARY KEY (id);


--
-- Name: users_profile users_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_user_id_key UNIQUE (user_id);


--
-- Name: users_user users_user_email_243f6e77_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_243f6e77_uniq UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_rut_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_rut_key UNIQUE (rut);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: vehicles_backupvehiculo vehicles_backupvehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_backupvehiculo
    ADD CONSTRAINT vehicles_backupvehiculo_pkey PRIMARY KEY (id);


--
-- Name: vehicles_evidenciaingreso vehicles_evidenciaingreso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_evidenciaingreso
    ADD CONSTRAINT vehicles_evidenciaingreso_pkey PRIMARY KEY (id);


--
-- Name: vehicles_historialvehiculo vehicles_historialvehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_historialvehiculo
    ADD CONSTRAINT vehicles_historialvehiculo_pkey PRIMARY KEY (id);


--
-- Name: vehicles_ingresovehiculo vehicles_ingresovehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_ingresovehiculo
    ADD CONSTRAINT vehicles_ingresovehiculo_pkey PRIMARY KEY (id);


--
-- Name: vehicles_vehiculo vehicles_vehiculo_patente_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_vehiculo
    ADD CONSTRAINT vehicles_vehiculo_patente_key UNIQUE (patente);


--
-- Name: vehicles_vehiculo vehicles_vehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_vehiculo
    ADD CONSTRAINT vehicles_vehiculo_pkey PRIMARY KEY (id);


--
-- Name: workorders_aprobacion workorders_aprobacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_aprobacion
    ADD CONSTRAINT workorders_aprobacion_pkey PRIMARY KEY (id);


--
-- Name: workorders_aprobacion workorders_aprobacion_presupuesto_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_aprobacion
    ADD CONSTRAINT workorders_aprobacion_presupuesto_id_key UNIQUE (presupuesto_id);


--
-- Name: workorders_auditoria workorders_auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_auditoria
    ADD CONSTRAINT workorders_auditoria_pkey PRIMARY KEY (id);


--
-- Name: workorders_bloqueovehiculo workorders_bloqueovehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_bloqueovehiculo
    ADD CONSTRAINT workorders_bloqueovehiculo_pkey PRIMARY KEY (id);


--
-- Name: workorders_checklist workorders_checklist_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_checklist
    ADD CONSTRAINT workorders_checklist_pkey PRIMARY KEY (id);


--
-- Name: workorders_comentarioot workorders_comentarioot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_comentarioot
    ADD CONSTRAINT workorders_comentarioot_pkey PRIMARY KEY (id);


--
-- Name: workorders_detallepresup workorders_detallepresup_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_detallepresup
    ADD CONSTRAINT workorders_detallepresup_pkey PRIMARY KEY (id);


--
-- Name: workorders_evidencia workorders_evidencia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_evidencia
    ADD CONSTRAINT workorders_evidencia_pkey PRIMARY KEY (id);


--
-- Name: workorders_itemot workorders_itemot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_itemot
    ADD CONSTRAINT workorders_itemot_pkey PRIMARY KEY (id);


--
-- Name: workorders_ordentrabajo workorders_ordentrabajo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_ordentrabajo
    ADD CONSTRAINT workorders_ordentrabajo_pkey PRIMARY KEY (id);


--
-- Name: workorders_pausa workorders_pausa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_pausa
    ADD CONSTRAINT workorders_pausa_pkey PRIMARY KEY (id);


--
-- Name: workorders_presupuesto workorders_presupuesto_ot_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_presupuesto
    ADD CONSTRAINT workorders_presupuesto_ot_id_key UNIQUE (ot_id);


--
-- Name: workorders_presupuesto workorders_presupuesto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_presupuesto
    ADD CONSTRAINT workorders_presupuesto_pkey PRIMARY KEY (id);


--
-- Name: workorders_versionevidencia workorders_versionevidencia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_versionevidencia
    ADD CONSTRAINT workorders_versionevidencia_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: drivers_cho_rut_726c7c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX drivers_cho_rut_726c7c_idx ON public.drivers_chofer USING btree (rut);


--
-- Name: drivers_cho_vehicul_7bd6e0_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX drivers_cho_vehicul_7bd6e0_idx ON public.drivers_chofer USING btree (vehiculo_asignado_id);


--
-- Name: drivers_cho_zona_8c4223_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX drivers_cho_zona_8c4223_idx ON public.drivers_chofer USING btree (zona, activo);


--
-- Name: drivers_chofer_rut_6468d63d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX drivers_chofer_rut_6468d63d_like ON public.drivers_chofer USING btree (rut varchar_pattern_ops);


--
-- Name: drivers_chofer_vehiculo_asignado_id_595a2fd3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX drivers_chofer_vehiculo_asignado_id_595a2fd3 ON public.drivers_chofer USING btree (vehiculo_asignado_id);


--
-- Name: drivers_his_chofer__4889bd_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX drivers_his_chofer__4889bd_idx ON public.drivers_historialasignacionvehiculo USING btree (chofer_id, activa);


--
-- Name: drivers_his_fecha_a_fa1c55_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX drivers_his_fecha_a_fa1c55_idx ON public.drivers_historialasignacionvehiculo USING btree (fecha_asignacion);


--
-- Name: drivers_his_vehicul_b472bb_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX drivers_his_vehicul_b472bb_idx ON public.drivers_historialasignacionvehiculo USING btree (vehiculo_id, activa);


--
-- Name: drivers_historialasignacionvehiculo_chofer_id_67856114; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX drivers_historialasignacionvehiculo_chofer_id_67856114 ON public.drivers_historialasignacionvehiculo USING btree (chofer_id);


--
-- Name: drivers_historialasignacionvehiculo_vehiculo_id_612c9df4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX drivers_historialasignacionvehiculo_vehiculo_id_612c9df4 ON public.drivers_historialasignacionvehiculo USING btree (vehiculo_id);


--
-- Name: emergencies_emergenciaruta_aprobador_id_d0b11fe1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emergencies_emergenciaruta_aprobador_id_d0b11fe1 ON public.emergencies_emergenciaruta USING btree (aprobador_id);


--
-- Name: emergencies_emergenciaruta_mecanico_asignado_id_cb5bbe5a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emergencies_emergenciaruta_mecanico_asignado_id_cb5bbe5a ON public.emergencies_emergenciaruta USING btree (mecanico_asignado_id);


--
-- Name: emergencies_emergenciaruta_solicitante_id_629249b7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emergencies_emergenciaruta_solicitante_id_629249b7 ON public.emergencies_emergenciaruta USING btree (solicitante_id);


--
-- Name: emergencies_emergenciaruta_supervisor_asignado_id_b8fe3b78; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emergencies_emergenciaruta_supervisor_asignado_id_b8fe3b78 ON public.emergencies_emergenciaruta USING btree (supervisor_asignado_id);


--
-- Name: emergencies_emergenciaruta_vehiculo_id_9e2a90da; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emergencies_emergenciaruta_vehiculo_id_9e2a90da ON public.emergencies_emergenciaruta USING btree (vehiculo_id);


--
-- Name: emergencies_estado_6bbee0_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emergencies_estado_6bbee0_idx ON public.emergencies_emergenciaruta USING btree (estado, fecha_solicitud);


--
-- Name: emergencies_mecanic_23a3a9_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emergencies_mecanic_23a3a9_idx ON public.emergencies_emergenciaruta USING btree (mecanico_asignado_id, estado);


--
-- Name: emergencies_vehicul_123b59_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emergencies_vehicul_123b59_idx ON public.emergencies_emergenciaruta USING btree (vehiculo_id, estado);


--
-- Name: emergencies_zona_73dcea_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emergencies_zona_73dcea_idx ON public.emergencies_emergenciaruta USING btree (zona, estado);


--
-- Name: inventory_h_ot_id_bf6be8_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_h_ot_id_bf6be8_idx ON public.inventory_historialrepuestovehiculo USING btree (ot_id);


--
-- Name: inventory_h_repuest_12fb1b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_h_repuest_12fb1b_idx ON public.inventory_historialrepuestovehiculo USING btree (repuesto_id, fecha_uso);


--
-- Name: inventory_h_vehicul_076e14_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_h_vehicul_076e14_idx ON public.inventory_historialrepuestovehiculo USING btree (vehiculo_id, fecha_uso);


--
-- Name: inventory_historialrepuestovehiculo_item_ot_id_663c1daf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_historialrepuestovehiculo_item_ot_id_663c1daf ON public.inventory_historialrepuestovehiculo USING btree (item_ot_id);


--
-- Name: inventory_historialrepuestovehiculo_ot_id_4cd2a409; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_historialrepuestovehiculo_ot_id_4cd2a409 ON public.inventory_historialrepuestovehiculo USING btree (ot_id);


--
-- Name: inventory_historialrepuestovehiculo_repuesto_id_05222ff8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_historialrepuestovehiculo_repuesto_id_05222ff8 ON public.inventory_historialrepuestovehiculo USING btree (repuesto_id);


--
-- Name: inventory_historialrepuestovehiculo_vehiculo_id_8043ed77; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_historialrepuestovehiculo_vehiculo_id_8043ed77 ON public.inventory_historialrepuestovehiculo USING btree (vehiculo_id);


--
-- Name: inventory_m_fecha_867d0f_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_m_fecha_867d0f_idx ON public.inventory_movimientostock USING btree (fecha);


--
-- Name: inventory_m_ot_id_587757_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_m_ot_id_587757_idx ON public.inventory_movimientostock USING btree (ot_id, vehiculo_id);


--
-- Name: inventory_m_repuest_c6decf_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_m_repuest_c6decf_idx ON public.inventory_movimientostock USING btree (repuesto_id, fecha);


--
-- Name: inventory_m_tipo_31b222_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_m_tipo_31b222_idx ON public.inventory_movimientostock USING btree (tipo, fecha);


--
-- Name: inventory_movimientostock_item_ot_id_db2e8aab; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_movimientostock_item_ot_id_db2e8aab ON public.inventory_movimientostock USING btree (item_ot_id);


--
-- Name: inventory_movimientostock_ot_id_1893160a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_movimientostock_ot_id_1893160a ON public.inventory_movimientostock USING btree (ot_id);


--
-- Name: inventory_movimientostock_repuesto_id_193344ad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_movimientostock_repuesto_id_193344ad ON public.inventory_movimientostock USING btree (repuesto_id);


--
-- Name: inventory_movimientostock_usuario_id_166d033e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_movimientostock_usuario_id_166d033e ON public.inventory_movimientostock USING btree (usuario_id);


--
-- Name: inventory_movimientostock_vehiculo_id_870c451d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_movimientostock_vehiculo_id_870c451d ON public.inventory_movimientostock USING btree (vehiculo_id);


--
-- Name: inventory_r_categor_c569ca_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_r_categor_c569ca_idx ON public.inventory_repuesto USING btree (categoria, activo);


--
-- Name: inventory_r_codigo_522d7b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_r_codigo_522d7b_idx ON public.inventory_repuesto USING btree (codigo);


--
-- Name: inventory_repuesto_codigo_118f38ae_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_repuesto_codigo_118f38ae_like ON public.inventory_repuesto USING btree (codigo varchar_pattern_ops);


--
-- Name: inventory_s_cantida_3c062e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_s_cantida_3c062e_idx ON public.inventory_stock USING btree (cantidad_actual);


--
-- Name: inventory_s_estado_5b5e2b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_s_estado_5b5e2b_idx ON public.inventory_solicitudrepuesto USING btree (estado, fecha_solicitud);


--
-- Name: inventory_s_ot_id_7ef144_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_s_ot_id_7ef144_idx ON public.inventory_solicitudrepuesto USING btree (ot_id, estado);


--
-- Name: inventory_s_repuest_936160_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_s_repuest_936160_idx ON public.inventory_solicitudrepuesto USING btree (repuesto_id, estado);


--
-- Name: inventory_solicitudrepuesto_aprobador_id_692840f3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_solicitudrepuesto_aprobador_id_692840f3 ON public.inventory_solicitudrepuesto USING btree (aprobador_id);


--
-- Name: inventory_solicitudrepuesto_entregador_id_6f2a7c74; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_solicitudrepuesto_entregador_id_6f2a7c74 ON public.inventory_solicitudrepuesto USING btree (entregador_id);


--
-- Name: inventory_solicitudrepuesto_item_ot_id_08ce8cb6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_solicitudrepuesto_item_ot_id_08ce8cb6 ON public.inventory_solicitudrepuesto USING btree (item_ot_id);


--
-- Name: inventory_solicitudrepuesto_ot_id_36f06b58; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_solicitudrepuesto_ot_id_36f06b58 ON public.inventory_solicitudrepuesto USING btree (ot_id);


--
-- Name: inventory_solicitudrepuesto_repuesto_id_2e838912; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_solicitudrepuesto_repuesto_id_2e838912 ON public.inventory_solicitudrepuesto USING btree (repuesto_id);


--
-- Name: inventory_solicitudrepuesto_solicitante_id_09563de2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_solicitudrepuesto_solicitante_id_09563de2 ON public.inventory_solicitudrepuesto USING btree (solicitante_id);


--
-- Name: notificatio_creada__396ffc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notificatio_creada__396ffc_idx ON public.notifications_notification USING btree (creada_en);


--
-- Name: notificatio_usuario_8f60bb_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notificatio_usuario_8f60bb_idx ON public.notifications_notification USING btree (usuario_id, estado);


--
-- Name: notifications_notification_evidencia_id_65768f04; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_notification_evidencia_id_65768f04 ON public.notifications_notification USING btree (evidencia_id);


--
-- Name: notifications_notification_ot_id_3eb9c423; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_notification_ot_id_3eb9c423 ON public.notifications_notification USING btree (ot_id);


--
-- Name: notifications_notification_usuario_id_46cf25ef; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_notification_usuario_id_46cf25ef ON public.notifications_notification USING btree (usuario_id);


--
-- Name: scheduling__estado_fcfb41_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling__estado_fcfb41_idx ON public.scheduling_agenda USING btree (estado, fecha_programada);


--
-- Name: scheduling__fecha_aa77d1_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling__fecha_aa77d1_idx ON public.scheduling_cupodiario USING btree (fecha, zona);


--
-- Name: scheduling__fecha_p_e6e3aa_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling__fecha_p_e6e3aa_idx ON public.scheduling_agenda USING btree (fecha_programada);


--
-- Name: scheduling__vehicul_57bd6c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling__vehicul_57bd6c_idx ON public.scheduling_agenda USING btree (vehiculo_id, estado);


--
-- Name: scheduling__zona_32be82_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling__zona_32be82_idx ON public.scheduling_agenda USING btree (zona, fecha_programada);


--
-- Name: scheduling_agenda_coordinador_id_46fba5a1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_agenda_coordinador_id_46fba5a1 ON public.scheduling_agenda USING btree (coordinador_id);


--
-- Name: scheduling_agenda_vehiculo_id_5a571efa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_agenda_vehiculo_id_5a571efa ON public.scheduling_agenda USING btree (vehiculo_id);


--
-- Name: unique_vehiculo_fecha_activa; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_vehiculo_fecha_activa ON public.scheduling_agenda USING btree (vehiculo_id, fecha_programada) WHERE ((estado)::text = ANY ((ARRAY['PROGRAMADA'::character varying, 'CONFIRMADA'::character varying, 'EN_PROCESO'::character varying])::text[]));


--
-- Name: users_passw_expires_853bc2_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_passw_expires_853bc2_idx ON public.users_passwordresettoken USING btree (expires_at);


--
-- Name: users_passw_token_42ae9c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_passw_token_42ae9c_idx ON public.users_passwordresettoken USING btree (token, used);


--
-- Name: users_passwordresettoken_token_8e777b0e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_passwordresettoken_token_8e777b0e_like ON public.users_passwordresettoken USING btree (token varchar_pattern_ops);


--
-- Name: users_passwordresettoken_user_id_2355945a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_passwordresettoken_user_id_2355945a ON public.users_passwordresettoken USING btree (user_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_rut_f091af2a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_rut_f091af2a_like ON public.users_user USING btree (rut varchar_pattern_ops);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: vehicles_ba_fecha_i_d4900a_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_ba_fecha_i_d4900a_idx ON public.vehicles_backupvehiculo USING btree (fecha_inicio);


--
-- Name: vehicles_ba_vehicul_30607d_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_ba_vehicul_30607d_idx ON public.vehicles_backupvehiculo USING btree (vehiculo_principal_id, estado);


--
-- Name: vehicles_ba_vehicul_e1ca30_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_ba_vehicul_e1ca30_idx ON public.vehicles_backupvehiculo USING btree (vehiculo_backup_id, estado);


--
-- Name: vehicles_backupvehiculo_ot_id_80c4e8cf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_backupvehiculo_ot_id_80c4e8cf ON public.vehicles_backupvehiculo USING btree (ot_id);


--
-- Name: vehicles_backupvehiculo_supervisor_id_b293acdd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_backupvehiculo_supervisor_id_b293acdd ON public.vehicles_backupvehiculo USING btree (supervisor_id);


--
-- Name: vehicles_backupvehiculo_vehiculo_backup_id_20d6920b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_backupvehiculo_vehiculo_backup_id_20d6920b ON public.vehicles_backupvehiculo USING btree (vehiculo_backup_id);


--
-- Name: vehicles_backupvehiculo_vehiculo_principal_id_e56f48f2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_backupvehiculo_vehiculo_principal_id_e56f48f2 ON public.vehicles_backupvehiculo USING btree (vehiculo_principal_id);


--
-- Name: vehicles_ev_ingreso_a28754_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_ev_ingreso_a28754_idx ON public.vehicles_evidenciaingreso USING btree (ingreso_id, tipo);


--
-- Name: vehicles_evidenciaingreso_ingreso_id_9d451917; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_evidenciaingreso_ingreso_id_9d451917 ON public.vehicles_evidenciaingreso USING btree (ingreso_id);


--
-- Name: vehicles_hi_tipo_ev_fd642c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_hi_tipo_ev_fd642c_idx ON public.vehicles_historialvehiculo USING btree (tipo_evento, creado_en);


--
-- Name: vehicles_hi_vehicul_e82fbc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_hi_vehicul_e82fbc_idx ON public.vehicles_historialvehiculo USING btree (vehiculo_id, creado_en);


--
-- Name: vehicles_historialvehiculo_backup_utilizado_id_d036f5b5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_historialvehiculo_backup_utilizado_id_d036f5b5 ON public.vehicles_historialvehiculo USING btree (backup_utilizado_id);


--
-- Name: vehicles_historialvehiculo_ot_id_75598316; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_historialvehiculo_ot_id_75598316 ON public.vehicles_historialvehiculo USING btree (ot_id);


--
-- Name: vehicles_historialvehiculo_supervisor_id_f57e23da; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_historialvehiculo_supervisor_id_f57e23da ON public.vehicles_historialvehiculo USING btree (supervisor_id);


--
-- Name: vehicles_historialvehiculo_vehiculo_id_98479a21; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_historialvehiculo_vehiculo_id_98479a21 ON public.vehicles_historialvehiculo USING btree (vehiculo_id);


--
-- Name: vehicles_in_fecha_i_2d9cb4_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_in_fecha_i_2d9cb4_idx ON public.vehicles_ingresovehiculo USING btree (fecha_ingreso);


--
-- Name: vehicles_in_vehicul_109199_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_in_vehicul_109199_idx ON public.vehicles_ingresovehiculo USING btree (vehiculo_id, fecha_ingreso);


--
-- Name: vehicles_ingresovehiculo_guardia_id_53a96b22; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_ingresovehiculo_guardia_id_53a96b22 ON public.vehicles_ingresovehiculo USING btree (guardia_id);


--
-- Name: vehicles_ingresovehiculo_guardia_salida_id_caa777d1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_ingresovehiculo_guardia_salida_id_caa777d1 ON public.vehicles_ingresovehiculo USING btree (guardia_salida_id);


--
-- Name: vehicles_ingresovehiculo_vehiculo_id_685d63ef; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_ingresovehiculo_vehiculo_id_685d63ef ON public.vehicles_ingresovehiculo USING btree (vehiculo_id);


--
-- Name: vehicles_ve_estado_707e75_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_ve_estado_707e75_idx ON public.vehicles_vehiculo USING btree (estado);


--
-- Name: vehicles_ve_marca_45cd2d_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_ve_marca_45cd2d_idx ON public.vehicles_vehiculo USING btree (marca, modelo);


--
-- Name: vehicles_vehiculo_patente_edeee876_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_vehiculo_patente_edeee876_like ON public.vehicles_vehiculo USING btree (patente varchar_pattern_ops);


--
-- Name: vehicles_vehiculo_supervisor_id_d5280433; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_vehiculo_supervisor_id_d5280433 ON public.vehicles_vehiculo USING btree (supervisor_id);


--
-- Name: workorders__accion_63404e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__accion_63404e_idx ON public.workorders_auditoria USING btree (accion);


--
-- Name: workorders__apertur_5d43a7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__apertur_5d43a7_idx ON public.workorders_ordentrabajo USING btree (apertura);


--
-- Name: workorders__es_auto_ce159c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__es_auto_ce159c_idx ON public.workorders_pausa USING btree (es_automatica);


--
-- Name: workorders__estado_359d13_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__estado_359d13_idx ON public.workorders_ordentrabajo USING btree (estado);


--
-- Name: workorders__estado_d9e771_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__estado_d9e771_idx ON public.workorders_bloqueovehiculo USING btree (estado, creado_en);


--
-- Name: workorders__evidenc_25c55f_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__evidenc_25c55f_idx ON public.workorders_versionevidencia USING btree (evidencia_original_id, invalidado_en);


--
-- Name: workorders__objeto__e313dc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__objeto__e313dc_idx ON public.workorders_auditoria USING btree (objeto_tipo, objeto_id);


--
-- Name: workorders__ot_id_205c52_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__ot_id_205c52_idx ON public.workorders_comentarioot USING btree (ot_id, creado_en);


--
-- Name: workorders__ot_id_46eb80_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__ot_id_46eb80_idx ON public.workorders_itemot USING btree (ot_id);


--
-- Name: workorders__ot_id_ca9db8_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__ot_id_ca9db8_idx ON public.workorders_pausa USING btree (ot_id, inicio);


--
-- Name: workorders__tipo_dbb9b9_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__tipo_dbb9b9_idx ON public.workorders_pausa USING btree (tipo, inicio);


--
-- Name: workorders__tipo_f2668c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__tipo_f2668c_idx ON public.workorders_itemot USING btree (tipo);


--
-- Name: workorders__ts_d3fa4e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__ts_d3fa4e_idx ON public.workorders_auditoria USING btree (ts);


--
-- Name: workorders__usuario_234602_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__usuario_234602_idx ON public.workorders_comentarioot USING btree (usuario_id, creado_en);


--
-- Name: workorders__vehicul_492cf9_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders__vehicul_492cf9_idx ON public.workorders_bloqueovehiculo USING btree (vehiculo_id, estado);


--
-- Name: workorders_aprobacion_sponsor_id_6be9f9c0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_aprobacion_sponsor_id_6be9f9c0 ON public.workorders_aprobacion USING btree (sponsor_id);


--
-- Name: workorders_auditoria_usuario_id_a364fc7a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_auditoria_usuario_id_a364fc7a ON public.workorders_auditoria USING btree (usuario_id);


--
-- Name: workorders_bloqueovehiculo_creado_por_id_a6f47299; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_bloqueovehiculo_creado_por_id_a6f47299 ON public.workorders_bloqueovehiculo USING btree (creado_por_id);


--
-- Name: workorders_bloqueovehiculo_resuelto_por_id_59d8d1b6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_bloqueovehiculo_resuelto_por_id_59d8d1b6 ON public.workorders_bloqueovehiculo USING btree (resuelto_por_id);


--
-- Name: workorders_bloqueovehiculo_vehiculo_id_636d9760; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_bloqueovehiculo_vehiculo_id_636d9760 ON public.workorders_bloqueovehiculo USING btree (vehiculo_id);


--
-- Name: workorders_checklist_ot_id_1540ecfc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_checklist_ot_id_1540ecfc ON public.workorders_checklist USING btree (ot_id);


--
-- Name: workorders_checklist_verificador_id_2c8e1c3f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_checklist_verificador_id_2c8e1c3f ON public.workorders_checklist USING btree (verificador_id);


--
-- Name: workorders_comentarioot_comentario_padre_id_27168eaf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_comentarioot_comentario_padre_id_27168eaf ON public.workorders_comentarioot USING btree (comentario_padre_id);


--
-- Name: workorders_comentarioot_ot_id_10cdf9b0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_comentarioot_ot_id_10cdf9b0 ON public.workorders_comentarioot USING btree (ot_id);


--
-- Name: workorders_comentarioot_usuario_id_3ccffaad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_comentarioot_usuario_id_3ccffaad ON public.workorders_comentarioot USING btree (usuario_id);


--
-- Name: workorders_detallepresup_presupuesto_id_280ae68e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_detallepresup_presupuesto_id_280ae68e ON public.workorders_detallepresup USING btree (presupuesto_id);


--
-- Name: workorders_evidencia_invalidado_por_id_2e5bae6d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_evidencia_invalidado_por_id_2e5bae6d ON public.workorders_evidencia USING btree (invalidado_por_id);


--
-- Name: workorders_evidencia_ot_id_28d4044a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_evidencia_ot_id_28d4044a ON public.workorders_evidencia USING btree (ot_id);


--
-- Name: workorders_evidencia_subido_por_id_a74b13a1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_evidencia_subido_por_id_a74b13a1 ON public.workorders_evidencia USING btree (subido_por_id);


--
-- Name: workorders_itemot_ot_id_202e15f8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_itemot_ot_id_202e15f8 ON public.workorders_itemot USING btree (ot_id);


--
-- Name: workorders_ordentrabajo_backup_id_18a3bb60; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_ordentrabajo_backup_id_18a3bb60 ON public.workorders_ordentrabajo USING btree (backup_id);


--
-- Name: workorders_ordentrabajo_chofer_id_6b6450b8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_ordentrabajo_chofer_id_6b6450b8 ON public.workorders_ordentrabajo USING btree (chofer_id);


--
-- Name: workorders_ordentrabajo_jefe_taller_id_4670116f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_ordentrabajo_jefe_taller_id_4670116f ON public.workorders_ordentrabajo USING btree (jefe_taller_id);


--
-- Name: workorders_ordentrabajo_mecanico_id_1d9639b8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_ordentrabajo_mecanico_id_1d9639b8 ON public.workorders_ordentrabajo USING btree (mecanico_id);


--
-- Name: workorders_ordentrabajo_responsable_id_ebcc266b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_ordentrabajo_responsable_id_ebcc266b ON public.workorders_ordentrabajo USING btree (responsable_id);


--
-- Name: workorders_ordentrabajo_supervisor_id_f5ff50e2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_ordentrabajo_supervisor_id_f5ff50e2 ON public.workorders_ordentrabajo USING btree (supervisor_id);


--
-- Name: workorders_ordentrabajo_vehiculo_id_0079b61b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_ordentrabajo_vehiculo_id_0079b61b ON public.workorders_ordentrabajo USING btree (vehiculo_id);


--
-- Name: workorders_pausa_ot_id_3936e351; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_pausa_ot_id_3936e351 ON public.workorders_pausa USING btree (ot_id);


--
-- Name: workorders_pausa_usuario_id_e34d87c8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_pausa_usuario_id_e34d87c8 ON public.workorders_pausa USING btree (usuario_id);


--
-- Name: workorders_versionevidencia_evidencia_original_id_6fd9cd5a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_versionevidencia_evidencia_original_id_6fd9cd5a ON public.workorders_versionevidencia USING btree (evidencia_original_id);


--
-- Name: workorders_versionevidencia_invalidado_por_id_0896855f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workorders_versionevidencia_invalidado_por_id_0896855f ON public.workorders_versionevidencia USING btree (invalidado_por_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: drivers_chofer drivers_chofer_vehiculo_asignado_id_595a2fd3_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers_chofer
    ADD CONSTRAINT drivers_chofer_vehiculo_asignado_id_595a2fd3_fk_vehicles_ FOREIGN KEY (vehiculo_asignado_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: drivers_historialasignacionvehiculo drivers_historialasi_chofer_id_67856114_fk_drivers_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers_historialasignacionvehiculo
    ADD CONSTRAINT drivers_historialasi_chofer_id_67856114_fk_drivers_c FOREIGN KEY (chofer_id) REFERENCES public.drivers_chofer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: drivers_historialasignacionvehiculo drivers_historialasi_vehiculo_id_612c9df4_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers_historialasignacionvehiculo
    ADD CONSTRAINT drivers_historialasi_vehiculo_id_612c9df4_fk_vehicles_ FOREIGN KEY (vehiculo_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emergencies_emergenciaruta emergencies_emergenc_aprobador_id_d0b11fe1_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emergencies_emergenciaruta
    ADD CONSTRAINT emergencies_emergenc_aprobador_id_d0b11fe1_fk_users_use FOREIGN KEY (aprobador_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emergencies_emergenciaruta emergencies_emergenc_mecanico_asignado_id_cb5bbe5a_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emergencies_emergenciaruta
    ADD CONSTRAINT emergencies_emergenc_mecanico_asignado_id_cb5bbe5a_fk_users_use FOREIGN KEY (mecanico_asignado_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emergencies_emergenciaruta emergencies_emergenc_ot_asociada_id_c09e9463_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emergencies_emergenciaruta
    ADD CONSTRAINT emergencies_emergenc_ot_asociada_id_c09e9463_fk_workorder FOREIGN KEY (ot_asociada_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emergencies_emergenciaruta emergencies_emergenc_solicitante_id_629249b7_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emergencies_emergenciaruta
    ADD CONSTRAINT emergencies_emergenc_solicitante_id_629249b7_fk_users_use FOREIGN KEY (solicitante_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emergencies_emergenciaruta emergencies_emergenc_supervisor_asignado__b8fe3b78_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emergencies_emergenciaruta
    ADD CONSTRAINT emergencies_emergenc_supervisor_asignado__b8fe3b78_fk_users_use FOREIGN KEY (supervisor_asignado_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emergencies_emergenciaruta emergencies_emergenc_vehiculo_id_9e2a90da_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emergencies_emergenciaruta
    ADD CONSTRAINT emergencies_emergenc_vehiculo_id_9e2a90da_fk_vehicles_ FOREIGN KEY (vehiculo_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_historialrepuestovehiculo inventory_historialr_item_ot_id_663c1daf_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_historialrepuestovehiculo
    ADD CONSTRAINT inventory_historialr_item_ot_id_663c1daf_fk_workorder FOREIGN KEY (item_ot_id) REFERENCES public.workorders_itemot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_historialrepuestovehiculo inventory_historialr_ot_id_4cd2a409_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_historialrepuestovehiculo
    ADD CONSTRAINT inventory_historialr_ot_id_4cd2a409_fk_workorder FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_historialrepuestovehiculo inventory_historialr_repuesto_id_05222ff8_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_historialrepuestovehiculo
    ADD CONSTRAINT inventory_historialr_repuesto_id_05222ff8_fk_inventory FOREIGN KEY (repuesto_id) REFERENCES public.inventory_repuesto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_historialrepuestovehiculo inventory_historialr_vehiculo_id_8043ed77_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_historialrepuestovehiculo
    ADD CONSTRAINT inventory_historialr_vehiculo_id_8043ed77_fk_vehicles_ FOREIGN KEY (vehiculo_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_movimientostock inventory_movimiento_item_ot_id_db2e8aab_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_movimientostock
    ADD CONSTRAINT inventory_movimiento_item_ot_id_db2e8aab_fk_workorder FOREIGN KEY (item_ot_id) REFERENCES public.workorders_itemot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_movimientostock inventory_movimiento_ot_id_1893160a_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_movimientostock
    ADD CONSTRAINT inventory_movimiento_ot_id_1893160a_fk_workorder FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_movimientostock inventory_movimiento_repuesto_id_193344ad_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_movimientostock
    ADD CONSTRAINT inventory_movimiento_repuesto_id_193344ad_fk_inventory FOREIGN KEY (repuesto_id) REFERENCES public.inventory_repuesto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_movimientostock inventory_movimiento_vehiculo_id_870c451d_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_movimientostock
    ADD CONSTRAINT inventory_movimiento_vehiculo_id_870c451d_fk_vehicles_ FOREIGN KEY (vehiculo_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_movimientostock inventory_movimientostock_usuario_id_166d033e_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_movimientostock
    ADD CONSTRAINT inventory_movimientostock_usuario_id_166d033e_fk_users_user_id FOREIGN KEY (usuario_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_solicitudrepuesto inventory_solicitudr_aprobador_id_692840f3_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_solicitudrepuesto
    ADD CONSTRAINT inventory_solicitudr_aprobador_id_692840f3_fk_users_use FOREIGN KEY (aprobador_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_solicitudrepuesto inventory_solicitudr_entregador_id_6f2a7c74_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_solicitudrepuesto
    ADD CONSTRAINT inventory_solicitudr_entregador_id_6f2a7c74_fk_users_use FOREIGN KEY (entregador_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_solicitudrepuesto inventory_solicitudr_item_ot_id_08ce8cb6_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_solicitudrepuesto
    ADD CONSTRAINT inventory_solicitudr_item_ot_id_08ce8cb6_fk_workorder FOREIGN KEY (item_ot_id) REFERENCES public.workorders_itemot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_solicitudrepuesto inventory_solicitudr_ot_id_36f06b58_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_solicitudrepuesto
    ADD CONSTRAINT inventory_solicitudr_ot_id_36f06b58_fk_workorder FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_solicitudrepuesto inventory_solicitudr_repuesto_id_2e838912_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_solicitudrepuesto
    ADD CONSTRAINT inventory_solicitudr_repuesto_id_2e838912_fk_inventory FOREIGN KEY (repuesto_id) REFERENCES public.inventory_repuesto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_solicitudrepuesto inventory_solicitudr_solicitante_id_09563de2_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_solicitudrepuesto
    ADD CONSTRAINT inventory_solicitudr_solicitante_id_09563de2_fk_users_use FOREIGN KEY (solicitante_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stock inventory_stock_repuesto_id_376dd6e6_fk_inventory_repuesto_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stock
    ADD CONSTRAINT inventory_stock_repuesto_id_376dd6e6_fk_inventory_repuesto_id FOREIGN KEY (repuesto_id) REFERENCES public.inventory_repuesto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notifi_evidencia_id_65768f04_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notifi_evidencia_id_65768f04_fk_workorder FOREIGN KEY (evidencia_id) REFERENCES public.workorders_evidencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notifi_ot_id_3eb9c423_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notifi_ot_id_3eb9c423_fk_workorder FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notification_usuario_id_46cf25ef_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_usuario_id_46cf25ef_fk_users_user_id FOREIGN KEY (usuario_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: scheduling_agenda scheduling_agenda_coordinador_id_46fba5a1_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_agenda
    ADD CONSTRAINT scheduling_agenda_coordinador_id_46fba5a1_fk_users_user_id FOREIGN KEY (coordinador_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: scheduling_agenda scheduling_agenda_ot_asociada_id_ca818c5d_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_agenda
    ADD CONSTRAINT scheduling_agenda_ot_asociada_id_ca818c5d_fk_workorder FOREIGN KEY (ot_asociada_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: scheduling_agenda scheduling_agenda_vehiculo_id_5a571efa_fk_vehicles_vehiculo_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_agenda
    ADD CONSTRAINT scheduling_agenda_vehiculo_id_5a571efa_fk_vehicles_vehiculo_id FOREIGN KEY (vehiculo_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_passwordresettoken users_passwordresettoken_user_id_2355945a_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_passwordresettoken
    ADD CONSTRAINT users_passwordresettoken_user_id_2355945a_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_profile users_profile_user_id_2112e78d_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_user_id_2112e78d_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_backupvehiculo vehicles_backupvehic_ot_id_80c4e8cf_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_backupvehiculo
    ADD CONSTRAINT vehicles_backupvehic_ot_id_80c4e8cf_fk_workorder FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_backupvehiculo vehicles_backupvehic_vehiculo_backup_id_20d6920b_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_backupvehiculo
    ADD CONSTRAINT vehicles_backupvehic_vehiculo_backup_id_20d6920b_fk_vehicles_ FOREIGN KEY (vehiculo_backup_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_backupvehiculo vehicles_backupvehic_vehiculo_principal_i_e56f48f2_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_backupvehiculo
    ADD CONSTRAINT vehicles_backupvehic_vehiculo_principal_i_e56f48f2_fk_vehicles_ FOREIGN KEY (vehiculo_principal_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_backupvehiculo vehicles_backupvehiculo_supervisor_id_b293acdd_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_backupvehiculo
    ADD CONSTRAINT vehicles_backupvehiculo_supervisor_id_b293acdd_fk_users_user_id FOREIGN KEY (supervisor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_evidenciaingreso vehicles_evidenciain_ingreso_id_9d451917_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_evidenciaingreso
    ADD CONSTRAINT vehicles_evidenciain_ingreso_id_9d451917_fk_vehicles_ FOREIGN KEY (ingreso_id) REFERENCES public.vehicles_ingresovehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_historialvehiculo vehicles_historialve_backup_utilizado_id_d036f5b5_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_historialvehiculo
    ADD CONSTRAINT vehicles_historialve_backup_utilizado_id_d036f5b5_fk_vehicles_ FOREIGN KEY (backup_utilizado_id) REFERENCES public.vehicles_backupvehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_historialvehiculo vehicles_historialve_ot_id_75598316_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_historialvehiculo
    ADD CONSTRAINT vehicles_historialve_ot_id_75598316_fk_workorder FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_historialvehiculo vehicles_historialve_supervisor_id_f57e23da_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_historialvehiculo
    ADD CONSTRAINT vehicles_historialve_supervisor_id_f57e23da_fk_users_use FOREIGN KEY (supervisor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_historialvehiculo vehicles_historialve_vehiculo_id_98479a21_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_historialvehiculo
    ADD CONSTRAINT vehicles_historialve_vehiculo_id_98479a21_fk_vehicles_ FOREIGN KEY (vehiculo_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_ingresovehiculo vehicles_ingresovehi_guardia_salida_id_caa777d1_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_ingresovehiculo
    ADD CONSTRAINT vehicles_ingresovehi_guardia_salida_id_caa777d1_fk_users_use FOREIGN KEY (guardia_salida_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_ingresovehiculo vehicles_ingresovehi_vehiculo_id_685d63ef_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_ingresovehiculo
    ADD CONSTRAINT vehicles_ingresovehi_vehiculo_id_685d63ef_fk_vehicles_ FOREIGN KEY (vehiculo_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_ingresovehiculo vehicles_ingresovehiculo_guardia_id_53a96b22_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_ingresovehiculo
    ADD CONSTRAINT vehicles_ingresovehiculo_guardia_id_53a96b22_fk_users_user_id FOREIGN KEY (guardia_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles_vehiculo vehicles_vehiculo_supervisor_id_d5280433_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles_vehiculo
    ADD CONSTRAINT vehicles_vehiculo_supervisor_id_d5280433_fk_users_user_id FOREIGN KEY (supervisor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_aprobacion workorders_aprobacio_presupuesto_id_7f8c3bc3_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_aprobacion
    ADD CONSTRAINT workorders_aprobacio_presupuesto_id_7f8c3bc3_fk_workorder FOREIGN KEY (presupuesto_id) REFERENCES public.workorders_presupuesto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_aprobacion workorders_aprobacion_sponsor_id_6be9f9c0_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_aprobacion
    ADD CONSTRAINT workorders_aprobacion_sponsor_id_6be9f9c0_fk_users_user_id FOREIGN KEY (sponsor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_auditoria workorders_auditoria_usuario_id_a364fc7a_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_auditoria
    ADD CONSTRAINT workorders_auditoria_usuario_id_a364fc7a_fk_users_user_id FOREIGN KEY (usuario_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_bloqueovehiculo workorders_bloqueove_creado_por_id_a6f47299_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_bloqueovehiculo
    ADD CONSTRAINT workorders_bloqueove_creado_por_id_a6f47299_fk_users_use FOREIGN KEY (creado_por_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_bloqueovehiculo workorders_bloqueove_resuelto_por_id_59d8d1b6_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_bloqueovehiculo
    ADD CONSTRAINT workorders_bloqueove_resuelto_por_id_59d8d1b6_fk_users_use FOREIGN KEY (resuelto_por_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_bloqueovehiculo workorders_bloqueove_vehiculo_id_636d9760_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_bloqueovehiculo
    ADD CONSTRAINT workorders_bloqueove_vehiculo_id_636d9760_fk_vehicles_ FOREIGN KEY (vehiculo_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_checklist workorders_checklist_ot_id_1540ecfc_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_checklist
    ADD CONSTRAINT workorders_checklist_ot_id_1540ecfc_fk_workorder FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_checklist workorders_checklist_verificador_id_2c8e1c3f_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_checklist
    ADD CONSTRAINT workorders_checklist_verificador_id_2c8e1c3f_fk_users_user_id FOREIGN KEY (verificador_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_comentarioot workorders_comentari_comentario_padre_id_27168eaf_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_comentarioot
    ADD CONSTRAINT workorders_comentari_comentario_padre_id_27168eaf_fk_workorder FOREIGN KEY (comentario_padre_id) REFERENCES public.workorders_comentarioot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_comentarioot workorders_comentari_ot_id_10cdf9b0_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_comentarioot
    ADD CONSTRAINT workorders_comentari_ot_id_10cdf9b0_fk_workorder FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_comentarioot workorders_comentarioot_usuario_id_3ccffaad_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_comentarioot
    ADD CONSTRAINT workorders_comentarioot_usuario_id_3ccffaad_fk_users_user_id FOREIGN KEY (usuario_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_detallepresup workorders_detallepr_presupuesto_id_280ae68e_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_detallepresup
    ADD CONSTRAINT workorders_detallepr_presupuesto_id_280ae68e_fk_workorder FOREIGN KEY (presupuesto_id) REFERENCES public.workorders_presupuesto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_evidencia workorders_evidencia_invalidado_por_id_2e5bae6d_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_evidencia
    ADD CONSTRAINT workorders_evidencia_invalidado_por_id_2e5bae6d_fk_users_use FOREIGN KEY (invalidado_por_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_evidencia workorders_evidencia_ot_id_28d4044a_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_evidencia
    ADD CONSTRAINT workorders_evidencia_ot_id_28d4044a_fk_workorder FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_evidencia workorders_evidencia_subido_por_id_a74b13a1_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_evidencia
    ADD CONSTRAINT workorders_evidencia_subido_por_id_a74b13a1_fk_users_user_id FOREIGN KEY (subido_por_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_itemot workorders_itemot_ot_id_202e15f8_fk_workorders_ordentrabajo_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_itemot
    ADD CONSTRAINT workorders_itemot_ot_id_202e15f8_fk_workorders_ordentrabajo_id FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_ordentrabajo workorders_ordentrab_backup_id_18a3bb60_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_ordentrabajo
    ADD CONSTRAINT workorders_ordentrab_backup_id_18a3bb60_fk_vehicles_ FOREIGN KEY (backup_id) REFERENCES public.vehicles_backupvehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_ordentrabajo workorders_ordentrab_jefe_taller_id_4670116f_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_ordentrabajo
    ADD CONSTRAINT workorders_ordentrab_jefe_taller_id_4670116f_fk_users_use FOREIGN KEY (jefe_taller_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_ordentrabajo workorders_ordentrab_responsable_id_ebcc266b_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_ordentrabajo
    ADD CONSTRAINT workorders_ordentrab_responsable_id_ebcc266b_fk_users_use FOREIGN KEY (responsable_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_ordentrabajo workorders_ordentrab_vehiculo_id_0079b61b_fk_vehicles_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_ordentrabajo
    ADD CONSTRAINT workorders_ordentrab_vehiculo_id_0079b61b_fk_vehicles_ FOREIGN KEY (vehiculo_id) REFERENCES public.vehicles_vehiculo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_ordentrabajo workorders_ordentrabajo_chofer_id_6b6450b8_fk_drivers_chofer_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_ordentrabajo
    ADD CONSTRAINT workorders_ordentrabajo_chofer_id_6b6450b8_fk_drivers_chofer_id FOREIGN KEY (chofer_id) REFERENCES public.drivers_chofer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_ordentrabajo workorders_ordentrabajo_mecanico_id_1d9639b8_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_ordentrabajo
    ADD CONSTRAINT workorders_ordentrabajo_mecanico_id_1d9639b8_fk_users_user_id FOREIGN KEY (mecanico_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_ordentrabajo workorders_ordentrabajo_supervisor_id_f5ff50e2_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_ordentrabajo
    ADD CONSTRAINT workorders_ordentrabajo_supervisor_id_f5ff50e2_fk_users_user_id FOREIGN KEY (supervisor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_pausa workorders_pausa_ot_id_3936e351_fk_workorders_ordentrabajo_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_pausa
    ADD CONSTRAINT workorders_pausa_ot_id_3936e351_fk_workorders_ordentrabajo_id FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_pausa workorders_pausa_usuario_id_e34d87c8_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_pausa
    ADD CONSTRAINT workorders_pausa_usuario_id_e34d87c8_fk_users_user_id FOREIGN KEY (usuario_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_presupuesto workorders_presupues_ot_id_56fd5f45_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_presupuesto
    ADD CONSTRAINT workorders_presupues_ot_id_56fd5f45_fk_workorder FOREIGN KEY (ot_id) REFERENCES public.workorders_ordentrabajo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_versionevidencia workorders_versionev_evidencia_original_i_6fd9cd5a_fk_workorder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_versionevidencia
    ADD CONSTRAINT workorders_versionev_evidencia_original_i_6fd9cd5a_fk_workorder FOREIGN KEY (evidencia_original_id) REFERENCES public.workorders_evidencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workorders_versionevidencia workorders_versionev_invalidado_por_id_0896855f_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workorders_versionevidencia
    ADD CONSTRAINT workorders_versionev_invalidado_por_id_0896855f_fk_users_use FOREIGN KEY (invalidado_por_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict RfUTt0lkB8sjFb6mNBjm319lO5RV79LKbaAtAZXjdMCHPbwyO3KhvokS7kV6V8A

