# Generated by Django 5.2.7 on 2025-11-18 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorders', '0008_alter_evidencia_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('EVIDENCIA_SUBIDA', 'Evidencia Subida'), ('OT_CREADA', 'OT Creada'), ('OT_CERRADA', 'OT Cerrada'), ('OT_ASIGNADA', 'OT Asignada'), ('OT_EN_PAUSA', 'OT en Pausa'), ('OT_EN_QA', 'OT en QA'), ('OT_RETRABAJO', 'OT Retrabajo'), ('OT_APROBADA', 'OT Aprobada'), ('OT_RECHAZADA', 'OT Rechazada'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('NO_LEIDA', 'No Leída'), ('LEIDA', 'Leída'), ('ARCHIVADA', 'Archivada')], default='NO_LEIDA', max_length=15)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='workorders.evidencia')),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='workorders.ordentrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='notificatio_usuario_8f60bb_idx'), models.Index(fields=['creada_en'], name='notificatio_creada__396ffc_idx')],
            },
        ),
    ]
